<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class UserAdd extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Ajout Utilisateur';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Ajout Utilisateur</h1>
        <form action="" method="post">
            <span>
                <label for="email">Email</label>
                <input type="email" name="email" id="email" placeholder="Email" required>
            </span>
            <span>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" id="firstname" placeholder="Prénom" required>
            </span>
            <span>
                <label for="lastname">Nom</label>
                <input type="text" name="lastname" id="lastname" placeholder="Nom" required>
            </span>
            <span>
                <label for="birthday">Date de naissance</label>
                <input type="date" name="birthday" id="birthday" placeholder="Date de naissance" required>
            </span>
            <span>
                <label for="gender">Genre</label>
                <select name="gender" id="gender" required>
                    <option value="" disabled selected>Sélectionner un genre</option>
                    <option value="male">Homme</option>
                    <option value="female">Femme</option>
                    <option value="other">Autre</option>
                </select>
            </span>
            <span>
                <label for="password">Mot de passe</label>
                <input name="password" id="password" placeholder="Mot de passe" required>
            </span>
            <span>
                <label for="group">Groupe</label>
                <select name="group" id="group" required>
                    <option value="" disabled selected>Sélectionner un groupe</option>
                    <?= $this->showOptions($this->get('groupsOptions')); ?>
                </select>
            </span>
            <span>
                <label for="active">Statut</label>
                <select name="active" id="active" required>
                    <option value="" disabled selected>Sélectionner un statut</option>
                    <option value="1">Actif</option>
                    <option value="0">Inactif</option>
                </select>
            </span>
            <p><?= $this->get('error') ?? null ?></p>
            <button type="submit">Ajouter</button>
        </form>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}