<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class User extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Utilisateur';

    public function render() {
        $this->head();
        $this->header();
        ?>
        <main>
        <h1>Utilisateur : <?= $this->get('user')->getPk(); ?></h1>
        <ul>
            <li>Prénom : <?= $this->get('user')->get('firstname'); ?></li>
            <li>Nom : <?= $this->get('user')->get('lastname'); ?></li>
            <li>Anniversaire : <?= $this->get('user')->get('birthday'); ?></li>
            <li>Genre : <?= $this->get('user')->get('gender'); ?></li>
            <li>Groupe : <?= $this->get('user')->get('group'); ?></li>
            <li>Actif : <?= $this->get('user')->get('active'); ?></li>
        </ul>
        <a href="/admin/user/<?= $this->get('user')->getPk(); ?>/edit">Modifier</a>
        <a href="/admin/user/<?= $this->get('user')->getPk(); ?>/delete">Supprimer</a>
        <?= !$this->get('user')->get('active') ? '<a href="/admin/user/' . $this->get('user')->getPk() . '/confirm">Activer</a>' : ''; ?>
        <a href="/admin/users">Retour</a>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}