<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Account extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Mon compte';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
        <h1>Bonjour <?= $this->get('user')->get('firstname'); ?></h1>

        <?php $this->footer(); ?>
        </main>
        <!-- <script src="/js/views/account.js" type="module" namespace="account"></script> -->
        </body>
        </html>
        <?php
    }
}
