<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Account extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Mon compte';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
            <br>
        <h1>Bonjour <?= $this->get('user')->get('firstname'); ?></h1>
            <br>
            <br>
            <br>
            <section class="title-container">
                <h2 id="selection">Recommandé pour vous</h2>
                <br>
                <iframe width="1120" height="630"
                        src="https://www.youtube.com/embed/mtolAJbj44s?controls=0?autoplay=1&loop=1&playlist=mtolAJbj44s"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowfullscreen></iframe>

            </section>

                <br>
                <br>
            <section class="favoris">
                <h2 id="liked">Mes favoris</h2>
                <br>
                <div class="row">
                    <div class="column">
                        <img src="/img/johnwick.jpeg" alt="John Wick" style="width:100%">
                    </div>
                </div>
            </section>

            <section class="dejavu">
                <h2 id="historique">Mon historique</h2>
                <br>

                <div class="carousel">
                    <div class="carousel-inner">
                        <img src="/img/avengers.jpeg" alt="Avenger Infinity War">
                        <img src="/img/johnwick.jpeg" alt="John Wick">
                        <img src="/img/interstellar.jpeg" alt="Interstellar">

                    </div>
                    <div class="carousel-nav">
                        <button id="prevButton">&#8249;</button>
                        <button id="nextButton">&#8250;</button>
                    </div>
                </div>

            </section>

        <?php $this->footer(); ?>
        </main>
        <!-- <script src="/js/views/account.js" type="module" namespace="account"></script> -->
        </body>
        </html>
        <?php
    }
}
