<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Billing extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Facturation';

    protected function render() {
        $this->head();
        $this->header();
        ?>
        <main>
            <br>
        <h1>Facturation</h1>
                <br>
            <div class="price-card">
                <h1 id="abonnement-titre">Prenium</h1>
                <div class="price text-center">
                    <h2 class="value">2€<span id="par-mois">/mo</span></h2>
                    <br>
                    <ul class="description">
                        <li> - Accès illimité à un large catalogue de films</li>
                        <br>
                        <li> - Sans publicités</li>
                        <br>
                        <li> - Qualité 4K (3840x2160p)</li>
                        <br>
                        <li> - Jusqu'à 2 sessions actives en simultanée</li>
                        <br>
                        <li class="gray"> - Devenez contributeur EAM+</li>
                        <br>
                        <li class="gray"> - Contenu exclusif en avant-première (accès beta...)</li>
                    </ul>
                </div>
                <div class="join">
                    <a href="/register" class="bouton">Choisir ce plan</a>
                </div>
        <?php
        $this->footer();
        ?>
    </main>
    <?php
    }
}