<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Billing extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Facturation';

    protected function render() {
        $this->head();
        $this->header();
        ?>
        <main>
        <h1>Facturation</h1>
        <h2>Abonnement premium</h2>
        <p>Abonnez-vous à notre service premium pour profiter de tous nos films et séries en illimité.</p>
        <h2>Abonnement contributeur</h2>
        <p>Abonnez-vous à notre service contributeur pour profiter de tous nos films et séries en illimité et pour pouvoir ajouter vos propres films et séries.</p>
        <?php
        $this->footer();
        ?>
    </main>
    <?php
    }
}