<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Login extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Connexion';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
            <br>
            <br>
            <br>
            <br>
        <form action="" method="post">
            <span>
                <label for="email">Email</label>
                <input type="email" name="email" id="email" placeholder="Email" required>
            </span>
            <span>
                <label for="password">Mot de passe</label>
                <input type="password" name="password" id="password" placeholder="Mot de passe" required>
            </span>
            <pre><?= $this->get('error') ?? null ?></pre>
            <button type="submit">Se connecter</button>
            <div class="login-register">
                <br>
                <p>Pas encore inscrit ? <a href="/register" class="register-link">S'inscrire</a></p>
            </div>
        </form>
        <?php $this->footer(); ?>
        </main>
        <script src="/js/views/login.js" type="module" namespace="login"></script>
        </body>
        </html>
        <?php
    }
}
