# routes for the App bundle
# route format:
# method | url | controller | action

# IndexController
get | / | AppBundle\Controllers\IndexController | indexAction
get | /about | AppBundle\Controllers\IndexController | aboutAction
get | /contact | AppBundle\Controllers\IndexController | contactAction
post | /contact | AppBundle\Controllers\IndexController | contactPostAction
get | /legal | AppBundle\Controllers\IndexController | legalAction
post | /theme | AppBundle\Controllers\IndexController | themePostAction

# DebugController
get | /debug | AppBundle\Controllers\DebugController | indexAction
get | /debug/phpinfo | AppBundle\Controllers\DebugController | phpinfoAction
get | /debug/routes | AppBundle\Controllers\DebugController| routesAction
get | /debug/logs | AppBundle\Controllers\DebugController | logsAction
get | /debug/log/{file} | AppBundle\Controllers\DebugController | logAction

# UserController
get | /register | AppBundle\Controllers\UserController | registerAction
post | /register | AppBundle\Controllers\UserController | registerPostAction
get | /login | AppBundle\Controllers\UserController | loginAction
post | /login | AppBundle\Controllers\UserController | loginPostAction
get | /logout | AppBundle\Controllers\UserController | logoutAction
get | /confirm/{email}/{token} | AppBundle\Controllers\UserController | confirmAction
get | /account | AppBundle\Controllers\UserController | accountAction

# SubscribeController
get | /billing | AppBundle\Controllers\SubscribeController | billingAction

# InvoiceController
# get | /invoice | AppBundle\Controllers\InvoiceController | indexAction
# get | /invoice/add | AppBundle\Controllers\InvoiceController | addInvoiceAction

# AdminController
get | /admin | AppBundle\Controllers\AdminController | indexAction
get | /admin/users | AppBundle\Controllers\AdminController | usersAction
get | /admin/user/add | AppBundle\Controllers\AdminController | userAddAction
post | /admin/user/add | AppBundle\Controllers\AdminController | userAddPostAction
get | /admin/user/{email} | AppBundle\Controllers\AdminController | userAction
get | /admin/user/{email}/edit | AppBundle\Controllers\AdminController | userEditAction
post | /admin/user/{email}/edit | AppBundle\Controllers\AdminController | userEditPostAction
get | /admin/user/{email}/delete | AppBundle\Controllers\AdminController | userDeleteAction
get | /admin/user/{email}/confirm | AppBundle\Controllers\AdminController | userConfirmAction
# get | /admin/groups | AppBundle\Controllers\AdminController | groupsAction
# get | /admin/group/{code} | AppBundle\Controllers\AdminController | groupAction
# get | /admin/group/{code}/edit | AppBundle\Controllers\AdminController | groupEditAction
# post | /admin/group/{code}/edit | AppBundle\Controllers\AdminController | groupEditPostAction
# get | /admin/group/{code}/delete | AppBundle\Controllers\AdminController | groupDeleteAction
# get | /admin/permissions | AppBundle\Controllers\AdminController | permissionsAction
# get | /admin/permission/{code} | AppBundle\Controllers\AdminController | permissionAction
# get | /admin/permission/{code}/edit | AppBundle\Controllers\AdminController | permissionEditAction
# post | /admin/permission/{code}/edit | AppBundle\Controllers\AdminController | permissionEditPostAction
# get | /admin/permission/{code}/delete | AppBundle\Controllers\AdminController | permissionDeleteAction

# ContributorController
get | /contributor | AppBundle\Controllers\ContributorController | indexAction
get | /contributions | AppBundle\Controllers\ContributorController | contributionsAction
get | /contribution/add | AppBundle\Controllers\ContributorController | contributionAddAction
post | /contribution/add | AppBundle\Controllers\ContributorController | contributionAddPostAction
get | /contribution/{id} | AppBundle\Controllers\ContributorController | contributionAction
get | /contribution/{id}/edit | AppBundle\Controllers\ContributorController | contributionEditAction
post | /contribution/{id}/edit | AppBundle\Controllers\ContributorController | contributionEditPostAction
get | /contribution/{id}/delete | AppBundle\Controllers\ContributorController | contributionDeleteAction

# 404 error action
any | /404/ | AppBundle\Controllers\IndexController | errorAction
