<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class ContributionAdd extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Ajouter une contribution';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Proposer un film</h1>
        <form action="/contribution/add" method="post" enctype="multipart/form-data">
            <span>
                <label for="title">Titre</label>
                <input type="text" name="title" id="title" required>
            </span>
            <span>
                <label for="director">Réalisateur(trice)</label>
                <textarea name="director" id="director" required></textarea>
            </span>
            <span>
                <label for="genre">Genre</label>
                <textarea name="genre" id="genre" required></textarea>
            </span>
            <span>
                <label for="date">Date de sortie</label>
                <input type="date" id="date" required></input>
            </span>
            <span>
                <label for="actor">Acteurs</label>
                <textarea name="actor" id="actor" required></textarea>
            </span>
            <span>
                <label for="review">Avis</label>
                <textarea name="review" id="review" required></textarea>
            </span>
            <span>
                <label for="image">Affiche</label>
                <input type="file" name="image" id="image" required>
            </span>
            <p>Formats d'images acceptés : <?= $this->listImageTypes(); ?></p>
            <input type="submit" value="Ajouter">
        </form>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }

    private function listImageTypes() : string {
        if (is_null($this->get('imagetypes'))) {
            return 'Aucun format d\'image disponible.';
        }
        $html = '';
        foreach ($this->get('imagetypes') as $imageType) {
            $html .= '.' . $imageType->get('receivedformat') . ', ';
        }
        return substr($html, 0, -2). '.';
    }
}