<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Debug extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Contributeur';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Contributeur</h1>
        <section>
            <h2>Contributions</h2>
            <p><a href="<?= HOME_URL; ?>/contributions">Contributions</a></p>
        </section>
        <section>
            <h2>Ajouter une contribution</h2>
            <p><a href="<?= HOME_URL; ?>/contributions/add">Ajouter une contribution</a></p>
        </section>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}