<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Admin extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Admin';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Admin</h1>
        <h2>Utilisateurs :</h2>
        <ul>
            <li><a href="/admin/users">Liste des utilisateurs</a></li>
            <li><a href="/admin/user/add">Créer un utilisateur</a></li>
        </ul>
        <h2>Groupes :</h2>
        <ul>
            <li><a href="/admin/groups" class="gray">Liste des groupes</a></li>
            <li><a href="/admin/group/add" class="gray">Créer un groupe</a></li>
        </ul>
        <h2>Contributions :</h2>
        <ul>
            <li><a href="/admin/contributions" class="gray">Liste des contributions</a></li>
            <li><a href="/admin/contribution/add" class="gray">Créer une contribution</a></li>
        </ul>
        <h2>Films :</h2>
        <ul>
            <li><a href="/admin/movies" class="gray">Liste des films</a></li>
            <li><a href="/admin/movie/add" class="gray">Créer un film</a></li>
        </ul>
        <h2>Genres :</h2>
        <ul>
            <li><a href="/admin/genres" class="gray">Liste des genres</a></li>
            <li><a href="/admin/genre/add" class="gray">Créer un genre</a></li>
        </ul>
        <h2>Factures :</h2>
        <ul>
            <li><a href="/admin/invoices" class="gray">Liste des factures</a></li>
            <li><a href="/admin/invoice/add" class="gray">Créer une facture</a></li>
        </ul>
        <h2>Permissions :</h2>
        <ul>
            <li><a href="/admin/permissions" class="gray">Liste des permissions</a></li>
            <li><a href="/admin/permission/add" class="gray">Créer une permission</a></li>
        </ul>
        <a href="/">Retour</a>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}