<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class UserAdd extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Ajout Utilisateur';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Ajout Utilisateur</h1>
        <form action="" method="post">
            <span>
                <label for="email">Email</label>
                <input type="email" name="email" id="email" placeholder="Email" required>
            </span>
            <span>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" id="firstname" placeholder="Prénom" required>
            </span>
            <span>
                <label for="lastname">Nom</label>
                <input type="text" name="lastname" id="lastname" placeholder="Nom" required>
            </span>
            <span>
                <label for="birthday">Date de naissance</label>
                <input type="date" name="birthday" id="birthday" placeholder="Date de naissance" required>
            </span>
            <span>
                <label for="gender">Genre</label>
                <select name="gender" id="gender" required>
                    <option value="" disabled selected>Sélectionner un genre</option>
                    <option value="male">Homme</option>
                    <option value="female">Femme</option>
                    <option value="other">Autre</option>
                </select>
            </span>
            <span>
                <label for="password">Mot de passe</label>
                <input type="password" name="password" id="password" placeholder="Mot de passe" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&\._])[A-Za-z\d@$!%*?&\._]{12,}$" required>
            </span>
            <span>
                <label for="passwordConfirm">Confirmer le mot de passe</label>
                <input type="password" name="passwordConfirm" id="passwordConfirm" placeholder="Confirmer le mot de passe" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&\._])[A-Za-z\d@$!%*?&\._]{12,}$" required>
            </span>
            <span>
                <label for="role">Groupe</label>
                <select name="role" id="role" required>
                    <option value="" disabled selected>Sélectionner un groupe</option>
                    <?= $this->get('groups')->showOptions(); ?>
                </select>
            </span>
            <span>
                <label for="status">Statut</label>
                <select name="status" id="status" required>
                    <option value="" disabled selected>Sélectionner un statut</option>
                    <option value="1">Actif</option>
                    <option value="0">Inactif</option>
                </select>
            </span>
            <pre><?= $this->get('error') ?? null ?></pre>
            <button type="submit">S'inscrire</button>
            <div class="login-connection">
                <br>
                <p>Déjà inscrit ? <a href="/login" class="register-link">Se connecter</a></p>
            </div>
        </form>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}