<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class User extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Utilisateur';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Utilisateur : <?= $this->get('user')->getPk(); ?></h1>
        <p><?= var_dump($this->get('user')->get()); ?></p>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}