<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Users extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Utilisateurs';

    public function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Utilisateurs</h1>
        <p><?= var_dump($this->get('users')); ?></p>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php 
    }
}