<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Contact extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Contact';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
        <h1>Contact</h1>
        <form action="/contact/" method="post">
        <span>
            <label for="name">Nom</label>
            <input type="text" name="name" id="name" required>
        </span>
        <span>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
        </span>
        <span>
            <label for="message">Message</label>
            <textarea name="message" id="message" required></textarea>
        </span>
        <pre>
        <?= $this->get('error'); ?>
        <?= $this->get('alert'); ?>
        </pre>
        <input type="submit" value="Envoyer">
        </form>
        </main>
        <?php $this->footer(); ?>
        </body>
        </html>
        <?php
    }
}
