<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Index extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Accueil';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
            <p><?= $this->get('error'); ?></p>
        <p><?= $this->get('alert'); ?></p>
            <section class="hidden">
                <h1 id="sub">Vos films préférés, pour seulement 4,99€ par mois.</h1>
            </section>

        </main>

        <?php $this->footer(); ?>
        <script src="/js/views/index.js" type="module" namespace="index"></script>
        </body>
        </html>
        <?php
    }
}
