<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class index extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Home';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
        <h1 id="title">Salut mon pote</h1>
        <p id="ping">Pinging API . . .</p>
        <p id="pong"></p>
        <button id="ping_button">Ping API</button>
        </main>
        <?php $this->postLoader(); ?>
        <script src="/js/views/index.js" type="module" namespace="index"></script>
        </body>
        </html>
        <?php
    }

}
