<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class Legal extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'CGU/CGV';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>    
        <main>
        <h1>CGU/CGV</h1>
        <p>Site réalisé par <?= DEV_NAME; ?>.</p>
        <p>Site réalisé dans le cadre du Cube N°3 au CESI Lyon.</p>
        <p>Site réalisé en PHP sans Framework.</p>
        <p>License MIT.</p>
        <?php $this->footer(); ?>
        </main>
        </body>
        </html>
        <?php
    }
}
