<?php

namespace AppBundle\Views;

use Framework\Components\View as View;

final class showRoutes extends View {
    use \AppBundle\Traits\ComponentsTrait;

    protected static string|null $defaultViewTitle = 'Debug - Routes';

    protected function render() {
        $this->head(); 
        $this->header();
        ?>
        <main>
        <h1>Routes</h1>
        <section>
        <h2>API</h2>
        <?php $this->routeTable($this->get('routesAPI')); ?>    
        </section>
        <section>
        <h2>Web</h2>
        <?php $this->routeTable($this->get('routes')); ?>
        </section>
        </main>
        <?php $this->postLoader(); ?>
        </body>
        </html>
        <?php
    }

    private function routeTable($routes) {
        ?>
        <table>
        <tr>
        <th>Route</th>
        <th>Controller</th>
        <th>Action</th>
        <th>Method</th>
        </tr>
        <?php foreach ($routes as $route): ?>            
        <tr>
        <td><a href="<?= HOME_URL . $route->getRoute(); ?>"><?= $route->getRoute(); ?></a></td>
        <td><?= $route->getController(); ?></td>
        <td><?= $route->getAction(); ?></td>
        <td><?= $route->getMethod(); ?></td>
        </tr>
        <?php endforeach; ?>
        </table>
        <?php
    }
}
